### ISSUE TITLE
portmidi sync not working on windows

### ISSUE THREAD

**Issue by grinsted** [x42/xjadeo#12]
I am trying to use xjadeo with propellerhead reason but am having no luck. Here's what I have been doing:

* I have installed loopmidi and created a virtual midi device. 
* I have setup reason to send MTC info to loopmidi.
* I have verified that loopmidi receives data from the loopmidi control panel. 
* I have verified that portmidi is receiving data by using the pmdefaults java app (from the portmidi interface) to see the "green lamp" blinking.
* I have started xjadeo, set it to sync to portmidi, and loaded up a video file, and verified that i can manually jog through it with the plus key. 

Result: xjadeo appears not to sync. 

I am not sure if i am doing something wrong, but i feel like i have tried everything. 

I am using: windows 10, xjadeo 0.8.5, reason 9.1, loopmidi 1.0.13, pmdefaults (from portmidi)

(i have also tried with other virtual midi devices such as loopbe1, but with no luck)

**Comment by grinsted** [comment]
I think it is not an xjadeo problem (but i still have no solution). I have tried to use midi-ox to debug and I find that:

* Midi-OX shows the correct "midi sync transport" meaning it does follow the play position in Reason.
* Midi-OX does not show the correct Midi Time Code. I dont know the difference - but it is two different windows in midiox. 

I am no expert and i do not know what the difference is between midi time code and midi sync transport. I can also set midi-ox to generate MTC's , and when i do that then xjadeo reacts.

**Comment by x42** [comment]
I don't know Reason,  but "midi sync transport" sounds like it's only  "Start, Stop" commands (probably Midi-Machine Control -- MMC)  and not actual Timecode (MTC).

xjadeo does not have its own transport mechanism (just start/stop won't work), xjadeo relies on a timecode-master to provide it with a timecode/clock.

A quick web-search lead me to http://www.mpc-forums.com/viewtopic.php?f=2&t=156414  which says that Reason cannot produce Timecode. (though that post is a couple of years old). 

I'm sorry I can't offer much help there.

**Comment by grinsted** [comment]
I found this explanation of various midi sync and time codes: http://tweakheadz.com/sync-mmc-mtc-smpte/
based on this then i think that Reason sends midi clock and SPP, but not MTC. So it is really not an xjadeo problem. Thanks
