### ISSUE TITLE
XJadeo won't sync to MTC

### ISSUE THREAD

**Issue by aaronbrownsound** [x42/xjadeo#26]
System: 
Win 10 64 bit
Reaper - sending MTC
PMDefault port midi
LoopMidi

I've confirmed that reaper is outputting MTC correctly to loop midi port B. Loop midi is set correctly in PMDefault port midi and the green light blinks.
XJadeo is set to port midi to sync.

However, it simply doesn't sync when playing. Something between PortMidi (PMDefault) and XJadeo are not connecting and it doesn't work.

I tried a restart and re-opening software as well. 

Any ideas how to get a 64 bit system to see PMDefault, or other connection besides Jack, to see each other and use MTC to control XJAdeo?

So close, yet so far :)
![brokenxjadeo](https://user-images.githubusercontent.com/8870408/40999728-4ced4f02-68d1-11e8-8ab2-eab9f3f89c0a.png)

**Comment by x42** [comment]
oops. xjadeo never used the default device -- fixed now in 22eaf9d464ea.

Could you try the attached binary, that should now honor the port-midi default device:
[xjadeo_installer_v0_8_7-6-g22eaf9d.zip](https://github.com/x42/xjadeo/files/2073909/xjadeo_installer_v0_8_7-6-g22eaf9d.zip)

**Comment by aaronbrownsound** [comment]
SUCCESS!!! That now sees everything!

The video has one other issue in that it shows an X across the screen every second or two. Is this common for a format issue or if the video doesn't adhere to the right frame rate? ( Think it's at some odd 23.8 frame rate)

![xjadeo_x](https://user-images.githubusercontent.com/8870408/41004197-abe1cbe8-68de-11e8-9a3e-198f2b21ad22.png)

For others reference, here are the steps I used to get it working using Reaper, XJAdeo, LoopMidi, and PMDefault (Port Midi).

[xjadeo.pdf](https://github.com/x42/xjadeo/files/2074104/xjadeo.pdf)

**Comment by x42** [comment]
Thanks for checking. I'll tag a new release with this fix -- 0.8.8 coming right up.

As for the "X" that means xjadeo cannot decode a video-frame for the given timecode. That may or may not be related to your video-file and MTC in this case (MTC only allows 24,25, 29.97df and 30 fps).

Can you share a snippet of a video-file that exhibits this issue? ideally attached to a new issue request, but private email works, too if you cannot share it publicly.

**Comment by aaronbrownsound** [comment]
Yeah, that's the issue. This is not a default time code and was captured from gameplay in a very odd, gameplay driven format. Can't share it, but it's a video problem. Thanks :)
