### ISSUE TITLE
Pro Tools on Mac mini M1

### ISSUE THREAD

**Issue by johansugarev** [x42/xjadeo#46]
Mac mini M1 base model, 11.4 + LG BX 55" via HDMI; Pro Tools Ultimate 2021.3 in sync with xjadeo. When it's playing a video on top, the screen or parts of it randomly flicker. Doesn't do it without the app running. Looks like this: https://youtu.be/yaGWh2Dalqk 
Any ideas?

**Comment by x42** [comment]
Jadeo still uses openGL, so perhaps this is due to some compatibility issues.

Is this the Intel CPU version? If so, perhaps try an experimental ARM/M1 CPU version: https://community.ardour.org/files/video-tools/jadeo-arm64-0.8.10.dmg

**Comment by johansugarev** [comment]
Thank's I'll try that, but I think I actually isolated it to the TV's PC mode. With PC mode off, it doesn't do it. Weird. Will investigate more. Wanted to use the chance to let you know the app is amazing.

**Comment by x42** [comment]
> I think I actually isolated it to the TV's PC mode

Nice find. That information may come in helpful down the road.

**Comment by kashenx** [comment]
> Jadeo still uses openGL, so perhaps this is due to some compatibility issues.
> 
> Is this the Intel CPU version? If so, perhaps try an experimental ARM/M1 CPU version: https://community.ardour.org/files/video-tools/jadeo-arm64-0.8.10.dmg
This version has no MTC（MIDI port）option 😭😭😭

**Comment by kashenx** [comment]
> Jadeo still uses openGL, so perhaps this is due to some compatibility issues.
> 
> Is this the Intel CPU version? If so, perhaps try an experimental ARM/M1 CPU version: https://community.ardour.org/files/video-tools/jadeo-arm64-0.8.10.dmg

This version has no MTC(MIDI port) option ? 😭😭😭😭

**Comment by johansugarev** [comment]
True. While I solved my flicker issue I’d love an arm version with MTC sync.
