### ISSUE TITLE
xjadeo doesn't follow transport timecode on OSX

### ISSUE THREAD

**Issue by lehtiniemi** [x42/xjadeo#5]
Hi! I'm trying out xjadeo with Bigwig that now supports Jack and acts as transport master, in hope to get video work alongside with Bitwig.

This works really well out of the box, but for some reason xjadeo doesn't follow the transport time code (each time I press stop and play again, it resumes from the position it was stopped in even though the transport starts from the beginning). I checked from qjackctl and the transport time code there follows Bitwig as it should so it's something with xjadeo. I have to hit backspace to manually rewind the video and this takes it to the start, which may not be the current transport position so this doesn't really work so well.

Should this work properly or is this yet a feature to be implemented, to make the video follow transport time code?

**Comment by x42** [comment]
Which version of xjadeo is that ?  `xjadeo --version`  on which OS?

Sounds like the video-codec of the file that you use is not properly supported by the built you have.
Can you include the output of  `ffprobe -i <video-file>`

**Comment by lehtiniemi** [comment]
Hi!

I'm running 0.8.0-rc3 on OSX Yosemite 10.10.3 and latest Jack2.

Here's the ffprobe output:

/Applications/ffprobe -i Tervasaari.mov
ffprobe version 2.7.1 Copyright (c) 2007-2015 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Tervasaari.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2014-07-01 21:02:59
  Duration: 00:01:26.42, start: 0.000000, bitrate: 95494 kb/s
    Stream #0:0(und): Video: prores (apcn / 0x6E637061), yuv422p10le(bt709), 1920x1080, 93127 kb/s, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)
    Metadata:
      creation_time   : 2014-07-01 21:02:59
      handler_name    : Core Media Data Handler
      encoder         : Apple ProRes 422
      timecode        : 00:00:00:00
    Stream #0:1(und): Audio: pcm_s24le (in24 / 0x34326E69), 48000 Hz, stereo, s32 (24 bit), 2304 kb/s (default)
    Metadata:
      creation_time   : 2014-07-01 21:02:59
      handler_name    : Core Media Data Handler
    Stream #0:2(und): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2014-07-01 21:02:59
      handler_name    : Core Media Data Handler
      timecode        : 00:00:00:00
Unsupported codec with id 0 for input stream 2


BUT I also tried converting this ProRes file to m4v using OSX context menu Convert audio/video with the option Better compability. This resulted the following probe, but still the video didn't follow transport:

/Applications/ffprobe -i Tervasaari.m4v
ffprobe version 2.7.1 Copyright (c) 2007-2015 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Tervasaari.m4v':
  Metadata:
    major_brand     : M4V 
    minor_version   : 1
    compatible_brands: M4V M4A mp42isom
    creation_time   : 2015-07-15 15:47:33
    encoder         : Mac OS X v10.10.3 (CMA 951, CM 1562.235, x86_64)
  Duration: 00:01:26.42, start: 0.000000, bitrate: 1439 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      creation_time   : 2015-07-15 15:47:33
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 640x360 [SAR 1:1 DAR 16:9], 1301 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 48k tbc (default)
    Metadata:
      creation_time   : 2015-07-15 15:47:33
      handler_name    : Core Media Video

**Comment by lehtiniemi** [comment]
Oh, also I don't have that xjadeo-file you mentioned, only Jadeo app that came with the OSX download. If that's relevant.

**Comment by x42** [comment]
Yeah that's fine, I expected Linux.

Ardour and Mixbux on OSX transcode the video-file to use mjpeg or mpeg4 video codec on import with a keyint_min 10.

Frame accurate seeking with h264 is always a bit of a gamble. Jadeo will at most decode 25 frames from a given keyframe (GOP must be < 1 sec) otherwise the decoder latency will become too large in particular when seeking backwards.

Jadeo should  refuse to open the file if it's larger , either that's a bug or that check was only added after the release candidate version that you currently use. I don't remember. I'll investigate on tomorrow. I'm sorry, busy just now and also away from a Mac.

If you have a minute please update to the latest version: 0.8.2.

**Comment by x42** [comment]
see #6
