### ISSUE TITLE
Do not link against libporttime.so

### ISSUE THREAD

**Issue by dvzrv** [x42/xjadeo#54]
Hi! I'm currently bumping [portmidi](https://github.com/PortMidi/portmidi) on Arch Linux and it seems that it does not provide the separate `libporttime.so` anymore, but instead everything seems to be covered by `libportmidi.so`.

Building fails, as autoconf still wants to link against `libporttime.so`. Removing this from `configure.ac` seems to work without issue.

**Comment by x42** [comment]
It's only used for windows.
On Linux in addition to JACK MIDI, ALSA sequencer is supported directly.
There is no need or use use portmidi indirection.

**Comment by dvzrv** [comment]
Ah excellent. Thanks for the clarification!
(took me some time to cycle back on this pkg)
