### ISSUE TITLE
MTC (portmidi) missing from arm MacOS version, available on intel version

### ISSUE THREAD

**Issue by adrienneteicher** [x42/xjadeo#55]
Upon updating to the latest arm MacOS version (0.8.12) I observed that MTC (portmidi) was not available. I roleld back to the arm version 0.8.11 but the option was missing there as well. Then I installed the intel version of 0.8.12 and MTC Portmidi is available again.

Running Ventura 13.4.1 (c)

**Comment by x42** [comment]
Fixed in 0.8.13
