### ISSUE TITLE
deleted issue?  xjadeo doesn't follow transport timecode on OSX 

### ISSUE THREAD

**Issue by x42** [x42/xjadeo#6]
There was a report about not being able to seek backwards with xjadeo when using Jadeo on OSX with Bitwig (#5) using ProRes or h264 files..

Gone..odd, it should not be possible to delete issues.

I can't reproduce.  Jadeo 0.8.2 , OSX 10.10.4. JACK 1.9.11 (JackPilot)

(1) Got the Bitwig Demo, v1.1.9 but on OSX the only option is CoreAudio, JACK is not avail.

(2) Tried ProRes and h264 QT generated files.  Can seek with JACK just fine.  Also disconnecting from JACK and manually seeking (press 'x' -> use slider) works.

**Comment by lehtiniemi** [comment]
It's back now: https://github.com/x42/xjadeo/issues/5

**Comment by lehtiniemi** [comment]
I tested this now: scrubbing works fine when disconnected as you said. Also, xjadeo follows Jack transport when I control it from the qjackctl. But when Bitwig is controlling the transport, qjackctl follows Bitwig transport but xjadeo doesn't follow what happens in qjackctl. What could cause this?

**Comment by x42** [comment]
That is very mysterious.  Does Bitwig just use portaudio's jack wrapper maybe?

Can you check with an Ardour Demo version http://nightly.ardour.org/  if Ardour + Bitwig are in sync? 
Ardour + Jadeo work here (both via JACK as well as Ardour directly controlling it).

Is the  Bitwig 1.2 beta publicly available?

Since you have qjackctl, I assume you use homebrew,  one explanation would be that you have two versions of libjack installed one from homebrew one from jackaudio.org.  or maybe bitwig wrongly ships one, too.   Different .dylibs could explain the issue. There must only ever be one libjack.dylib on the whole system.

You could try to run   
   /Applications/Jadeo.app/Contents/MacOS/Jadeo-bin --verbose
which prints jack polled timecode.  Other than that, I have no idea.

**Comment by lehtiniemi** [comment]
Thank you for the tips, I'll check this out. Meanwhile - how do I check the dynlib-issue - if I have duplicate, which one to keep and how to delete the extra one?

Bitwig beta isn't out yet as public but if I can backtrace it to them, I can report it as bug since I'm testing the beta.

**Comment by lehtiniemi** [comment]
Hi!

How I did further researching. I misread the qjackctl-transport - the Transport BBT is in sync with Bitwig, but the TIMECODE is in sync with xjadeo and doesn't reset. So xjadeo seems to be running correctly with qjackctl transport. How can the time code and BBT be separate? Shouldn't they run alongside each other automatically? Is this something Bitwig is doing wrong in their code?

**Comment by x42** [comment]
Is the timecode HH:MM:SS:FF (not BBT display) in sync with bitwig, qjackctl, xjadeo?


If not an educated guess is that it's a bigwig bug/feature. Let me explain.

Jack-transport is only a state (play, stop)  & absolute position in samples (timecode).

Then there can be at most one application that acts as "jack timebase-master" (first one wins). That applications is responsible to translate the current absolute timecode to Bar/Beat/Tick.

JACK itself cannot do that because the tempo and metrum can change anytime and it may also depend on the location in the song.

Jack transport (timecode) cannot varispeed (it always progresses at the rate of the soundcard when playing). All apps are "slaved" to it.  A user can only control it: Play now, Stop now, Locate to XX next cycle.  But jack always plays at speed 1.0 (samplerate) or is stopped.

One explanation would be that since Bitwig does a lot of varispeeding, it simply does not care about the absolute timecode. It just uses the state (play/stop) and forces its current BBT to jack regardless of the timecode.

**Comment by lehtiniemi** [comment]
Ah, thanks! qjackctl, xjadeo and Bitwig are in sync with the BBT, but Bitwig's timecode is out of sync with Jack timecode. So I think it's something Bitwig ignores. I've written a beta report about this and I hope they consider changing this. It would give video features to Bitwig if it's fixed so I would think there's some meaning. JACK is a new feature in the beta so I think it's still a work in progress.

Thank you so much for your help, now I know where the problem lies. I'll get back to you if Bitwig changes in this regards or should something else pop up. Thank you so much once more for your through answers. :)

Meanwhile, I can sync video with Bitwig by manually rewinding the scene each time. So it's really nice to have this, at least. And I hope they fix the time code sync eventually.

**Comment by x42** [comment]
PS. one solution for the vari-speed case is MTC (midi time code) generated by Bitwig.
xjadeo can also take that as sync-source.. or LTC (linear timecode, encoded as audio).

But musical time (Midi-clock or BBT) is not suitable for A/V sync.

I'll close this issue since it's not a xjadeo problem.

**Comment by lehtiniemi** [comment]
Hi!

Oh, Bitwig doesn't support MTC yet, unfortunately… but I'm sure it'll come eventually.

Thank you once again!

**Comment by sonority** [comment]
just for info: i have the same problem on Ubuntu 14.04 with Bitwig Studio 1.2 (stable) and xjadeo 0.7.6. with Ardour3 it is working without problems.

**Comment by lehtiniemi** [comment]
I reported this to Bitwig and they said they'll be able to fix this. I'll try to poke the issue so they don't forget.

    Juhana Lehtiniemi
    Film composer
    www.juhanalehtiniemi.com

**Comment by stephankellermayr** [comment]
...nothing changed with bitwig studio 2.0.
BBT is always in sync between BWS and qjackctl, but if you stop/play/loop in BWS, qjackctl does not reset the timecode and xjadeo starts playing from where it has been stopped.
The option "Act as transport sync master" in BWS settings does not really change this behaviour.
Communication between qjackctl and xjadeo seems to work correctly and if you reset the transport in qjackctl, xjadeo also resets the video to the beginning.
so it's still a bitwig bug... (?)

**Comment by x42** [comment]
I've heard that Bitwig 2.0 support MTC, maybe that's an option?
