### ISSUE TITLE
latest portmidi (-217) no longer builds libporttime.so

### ISSUE THREAD

**Issue by rugubara** [x42/xjadeo#8]
the build of xjadeo-0.8.5 (and 0.8.1) fails since there is no libporttime.so anymore. The dirty fix is:
`ln -s libportmidi.so libporttime.so`

Please update your build

**Comment by x42** [comment]
portmidi is only useful for windows builds of xjadeo (and maybe OSX).
What platform do you build xjadeo on?

**Comment by rugubara** [comment]
I build it on Gentoo linux

**Comment by x42** [comment]
use xjadeo's ALSA (native Linux) or JACK suppor.

PortMidi is not very useful on GNU/Linux  (configure with `--disable-portmidi` in case autodetection fails for some reason)
